name: build-and-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: build jar
        run: ./gradlew clean bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "build/libs/*.jar"
          target: "~/app"
          strip_components: 2
      
      - name: restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          script: |
            pkill -f 'java -jar' || true
            JAR=$(ls ~/app/*.jar | head -n 1)
            nohup java -jar "$JAR" --spring.profiles.active=prod \
              > ~/app/nohup.out 2>&1 &
